apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-development
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ilham.ellya@nawatech.co
    privateKeySecretRef:
      name: letsencrypt-development
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx